apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: mem1
  namespace: demo
spec:
  replicas: 3
  version: 1.5.3-alpine
  resources:
    requests:
      memory: 50Mi
  monitor:
    agent: coreos-prometheus-operator
    prometheus:
      namespace: demo
      labels:
        app: kubedb
      interval: 2s

