apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo4
  namespace: demo
spec:
  version: "3.4"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: prometheus.io/builtin
---
apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: e3
  namespace: demo
spec:
  version: "5.6"
  doNotPause: false
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: prometheus.io/builtin
---
apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: mem17
  namespace: demo
spec:
  replicas: 1
  version: "1.5.4"
  resources:
    requests:
      memory: 50Mi
  monitor:
    agent: prometheus.io/builtin
---
apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: m12
  namespace: demo
spec:
  version: "8.0"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: prometheus.io/builtin
---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: p3
  namespace: demo
spec:
  version: "9.6"
  doNotPause: false
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: prometheus.io/builtin
---
apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: r14
spec:
  version: "4"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 55Mi
  monitor:
    agent: prometheus.io/builtin