apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: p-xyz1
  namespace: demo
  labels:
    kubedb.com/kind: Postgres
spec:
  databaseName: p1
  storageSecretName: pg-snap-secret
  gcs:
    bucket: restic
