apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: r2
  namespace: demo
spec:
  version: 9.6
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    snapshotSource:
      name: p-xyz
