apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: p7
  namespace: demo
spec:
  version: 9.6.5
  doNotPause: false
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    scriptSource:
      gitRepo:
        repository: "https://github.com/kubedb/postgres-init-scripts.git"
        directory: .
