apiVersion: kubedb.com/v1alpha1
kind: Redis
metadata:
  name: r14
spec:
  version: 4
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 55Mi
