apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: e-xyz1
  namespace: demo
  labels:
    kubedb.com/kind: Elasticsearch
spec:
  databaseName: e1
  storageSecretName: es-snap-secret
  gcs:
    bucket: restic
