apiVersion: kubedb.com/v1alpha1
kind: Elasticsearch
metadata:
  name: e-wrong
  namespace: demo
spec:
  version: 5.6.5
  doNotPause: false
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
