apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: my-xyz
  namespace: demo
  labels:
    kubedb.com/kind: MySQL
spec:
  databaseName: m12
  storageSecretName: mg-snap-secret
  gcs:
    bucket: restic
