apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: back1
  namespace: demo
spec:
  version: 8.0
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    scriptSource:
      gitRepo:
        repository: "https://github.com/the-redback/mysql-init-script.git"
        directory: .
  backupSchedule:
    cronExpression: "@every 1m"
    storageSecretName: ms-snap-secret
    gcs:
      bucket: restic
