apiVersion: kubedb.com/v1alpha1
kind: Memcached
metadata:
  name: mc15
  namespace: demo
spec:
  replicas: 1
  version: "1.5.4"
  #nodeSelector:
  #  disktype: ssd
  #doNotPause: true
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: demo
      labels:
        app: kubedb
      interval: 10s
