apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: r4
  namespace: demo
spec:
  version: "3.4"
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  init:
    snapshotSource:
      name: mgo-xyz-6
      namespace: demo
