apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: m21
  namespace: demo
spec:
  version: 8.0
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    prometheus:
      namespace: demo
      labels:
        app: kubedb
      interval: 10s
