apiVersion: v1
kind: Namespace
metadata:
  name: demo

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: redis
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    role: master
    tier: backend
  namespace: demo
spec:
  type: LoadBalancer  
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master
    tier: backend
