apiVersion: kubedb.com/v1alpha1
kind: Snapshot
metadata:
  name: mgo-xyz
  namespace: demo
  labels:
    kubedb.com/kind: MongoDB
spec:
  databaseName: mgo2
  storageSecretName: my-snap-secret
  gcs:
    bucket: restic
