apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mg1
  namespace: demo
spec:
  version: 3.4
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  init:
    scriptSource:
      gitRepo:
        repository: "https://github.com/the-redback/k8s-mongodb-init-script.git"
        directory: .
