apiVersion: v1
kind: Namespace
metadata:
  name: demo
spec:
  finalizers:
  - kubernetes
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: mongodb
  name: mongodb
  namespace: demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        imagePullPolicy: Always
        name: mongodb
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "root"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "root"
        args:
          - --auth

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
  namespace: demo
spec:
  ports:
    - port: 27017
  selector:
    name: mongodb
  type: LoadBalancer  #To access from outside
