apiVersion: kubedb.com/v1alpha1
kind: MongoDB
metadata:
  name: mgo10
  namespace: demo
spec:
  version: 3.6
  replicas: 1
  storage:
    storageClassName: "standard"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Mi
  monitor:
    agent: prometheus.io/coreos-operator
    prometheus:
      namespace: demo
      port: 1024
      labels:
        app: kubedb
      interval: 10s
